name: UI Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the production branch
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    steps:
      - name: Git clone https://github.com/PSaiSoumya/CI-CD-test.git
        uses: actions/checkout@v2

      - name: Install And Build Our React App
        run: npm install && npm run build

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          SOURCE: "build/"
          HOST: ${{ secrets.LIGTHSAIL_IP }}
          USERNAME: ${{ secrets.LIGTHSAIL_USERNAME }}
          KEY: ${{ secrets.LIGTHSAIL_SSH_KEY }}
          PORT: 22
          TARGET: "/home/${{ secrets.LIGTHSAIL_USERNAME }}"

      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          HOST: ${{ secrets.LIGTHSAIL_IP }}
          USERNAME: ${{ secrets.LIGTHSAIL_USERNAME }}
          KEY: ${{ secrets.LIGTHSAIL_SSH_KEY }}
          PORT: 22
          SCRIPT: |
            sudo systemctl restart apache2
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
